
package com.akash.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "updatePatientPreferenceSOAP_v3_00QSService", targetNamespace = "http://optumrx.unitedhealthgroup.com/ABS/updatePatientPreference/v3_00", wsdlLocation = "file:/C:/Users/apande62/CoreJava/WebServiceProject/src/main/resources/wsdl/v3_00.wsdl")
public class UpdatePatientPreferenceSOAPV300QSService
    extends Service
{

    private final static URL UPDATEPATIENTPREFERENCESOAPV300QSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.akash.ws.UpdatePatientPreferenceSOAPV300QSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.akash.ws.UpdatePatientPreferenceSOAPV300QSService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/apande62/CoreJava/WebServiceProject/src/main/resources/wsdl/v3_00.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/apande62/CoreJava/WebServiceProject/src/main/resources/wsdl/v3_00.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        UPDATEPATIENTPREFERENCESOAPV300QSSERVICE_WSDL_LOCATION = url;
    }

    public UpdatePatientPreferenceSOAPV300QSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdatePatientPreferenceSOAPV300QSService() {
        super(UPDATEPATIENTPREFERENCESOAPV300QSSERVICE_WSDL_LOCATION, new QName("http://optumrx.unitedhealthgroup.com/ABS/updatePatientPreference/v3_00", "updatePatientPreferenceSOAP_v3_00QSService"));
    }

    /**
     * 
     * @return
     *     returns UpdatePatientPreferenceV300
     */
    @WebEndpoint(name = "updatePatientPreferenceSOAP_v3_00QSPort")
    public UpdatePatientPreferenceV300 getUpdatePatientPreferenceSOAPV300QSPort() {
        return super.getPort(new QName("http://optumrx.unitedhealthgroup.com/ABS/updatePatientPreference/v3_00", "updatePatientPreferenceSOAP_v3_00QSPort"), UpdatePatientPreferenceV300.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdatePatientPreferenceV300
     */
    @WebEndpoint(name = "updatePatientPreferenceSOAP_v3_00QSPort")
    public UpdatePatientPreferenceV300 getUpdatePatientPreferenceSOAPV300QSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://optumrx.unitedhealthgroup.com/ABS/updatePatientPreference/v3_00", "updatePatientPreferenceSOAP_v3_00QSPort"), UpdatePatientPreferenceV300.class, features);
    }

}
